---
- name: Namespace Check
  command: "kubectl apply -f {{ k8s_dir }}/namespace.yaml"

- name: Create secrets via kubectl
  shell: |
    kubectl create secret generic splitwise-secrets \
      --namespace={{ k8s_namespace }} \
      --from-literal=JWT_SECRET=\"{{ secret_jwt }}\" \
      --from-literal=MONGO_USERNAME=\"{{ secret_mongo_user }}\" \
      --from-literal=MONGO_PASSWORD=\"{{ secret_mongo_pass }}\" \
      --from-literal=REDIS_PASSWORD=\"{{ secret_redis_pass }}\" \
      --dry-run=client -o yaml | kubectl apply -f -

- name: Apply Base Infrastructure (Config, Mongo, Redis)
  command: "kubectl apply -f {{ k8s_dir }}/{{ item }}"
  with_items:
    - configmap.yaml
    - mongodb-statefulset.yaml
    - redis-deployment.yaml

- name: Check Database Readiness
  command: "kubectl rollout status {{ item }} -n {{ k8s_namespace }} --timeout=300s"
  with_items:
    - statefulset/mongodb
    - deployment/redis

- name: Apply Backend Components
  command: "kubectl apply -f {{ k8s_dir }}/{{ item }}"
  with_items:
    - backend-deployment.yaml
    - backend-service.yaml
    - backend-hpa.yaml

- name: Force Backend Restart
  command: "kubectl rollout restart deployment/backend -n {{ k8s_namespace }}"

- name: Apply Frontend
  command: "kubectl apply -f {{ k8s_dir }}/{{ item }}"
  with_items:
    - frontend-deployment.yaml


- name: Get deployment status
  command: kubectl get all -n {{ k8s_namespace }}
  register: status

- name: Display status
  debug:
    msg: "{{ status.stdout_lines }}"